#UDP client (rename this something sane!)
GXX=g++
CFLAGS=-g -std=c++11


all:	client3 server3

client3: client3.cc
	$(GXX) $(CFLAGS) client3.cc -o client3

server3: server3.cc
	$(GXX) $(CFLAGS) server3.cc -o server3
